version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: grocerystore
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    restart: always

  grocery-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grocery-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/grocerystore?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      LOGGING_LEVEL_ROOT: INFO
    ports:
      - "8088:8088"
    networks:
      - mynetwork
    restart: always